In [1]:
import numpy as np

##  Numpy Array


#### 1D array

#### 2D Array

#### List to np array and viceversa

#### Shape of array

#### Create array based on ranges

#### Array of Zeros, Ones, nonZeros

#### Identity Matrix

#### Numpy Broadcast

#### Create Evenly Space Distribution Array

#### Create Uniform distributed random number(means every number between 0 and 1 has a same probability of getting chosen)

#### Standard Normal  distribution random number(returns random values between -infinity and +inifinity. The random values would follow a normal distribution with a mean value 0 and a standard deviation 1.)

#### Create Random integer

#### Seed with Random number - It gives the same random number every time

#### Reshape 1D to 2D

#### Returns max and min value

#### Return index of max and min value

## Array Slicing

#### Slice row and column in 1D Array

#### Slice row and column in 2D Array

## Array Filter

#### Filter by Condition

## Operations

#### 2D sum, Row/column wise sum and mean

#### Understanding of Matrix Multiplication

#### Return a contiguous flattened array

#### Return a copy of flattened array from 2D array

#### Sort 1D, 2D array based on index

#### Unravel index , ravel_multi_index from stack overflow

In [2]:
X = np.array([[4,  2],
              [9,  3],
              [8,  5],
              [3,  3],
              [5,  6]])
X.shape = (5, 2)

Find, where all the value 3 presents in X


In [4]:
idx = np.where(X==3)
idx 

(array([1, 3, 3], dtype=int64), array([1, 0, 1], dtype=int64))

it returns the x, y of indices [because X is 2 dimensional]

If you apply ravel_multi_index for idx obtained

In [5]:
idx_flat = np.ravel_multi_index(idx, X.shape)
idx_flat

array([3, 6, 7], dtype=int64)

From the above example, we can understand,

ravel_multi_index converts multi-dimensional indices(nd array) into single-dimensional indices(linear array)
It works only on indices i.e. both input and output are indices
The result indices will be direct indices of X.ravel(). You can verify in the below x_linear

In [6]:
x_linear = X.ravel()
x_linear

array([4, 2, 9, 3, 8, 5, 3, 3, 5, 6])

Whereas, unravel_index is very simple, just reverse of above(np.ravel_multi_index)

In [9]:
idx = np.unravel_index(idx_flat , X.shape)
idx

(array([1, 3, 3], dtype=int64), array([1, 0, 1], dtype=int64))

which is same as idx = np.where(X==3)

unravel_index converts single-dimensional indices(linear array) into multi-dimensional indices(nd array)
It works only on indices i.e. both input and output are indices 