In [4]:
import numpy as np

##  Numpy Array


#### 1D array

In [10]:
np.array([3,6,5])

array([3, 6, 5])

#### 2D Array

In [11]:
np.array([[3,6,5],[8,9,10]])

array([[ 3,  6,  5],
       [ 8,  9, 10]])

#### List to np array and viceversa

In [13]:
list = [3,6,8]
list

[3, 6, 8]

In [14]:
np.array(list)

array([3, 6, 8])

#### Shape of array

In [15]:
arr = np.array([[3,6,5],[8,9,10]])
arr.shape

(2, 3)

#### Create array based on ranges

In [16]:
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

#### Array of Zeros, Ones, nonZeros

In [20]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.nonzero([4,5,0,9,0])

(array([0, 1, 3], dtype=int64),)

#### Identity Matrix

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Numpy Broadcast

In [24]:
arr = np.array([[3,4,5],[5,6,7]])
arr

array([[3, 4, 5],
       [5, 6, 7]])

In [25]:
arr + 100

array([[103, 104, 105],
       [105, 106, 107]])

In [26]:
arr * 5 

array([[15, 20, 25],
       [25, 30, 35]])

#### Create Evenly Space Distribution Array

In [79]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### Create Uniform distributed random number(means every number between 0 and 1 has a same probability of getting chosen)

In [31]:
np.random.rand(5,5)

array([[4.11820635e-01, 8.62682141e-01, 5.58506867e-01, 3.09860698e-01,
        2.71372091e-01],
       [9.77106069e-01, 6.36443192e-01, 6.40962766e-01, 1.49862924e-03,
        8.42200745e-01],
       [9.64383880e-01, 6.11411309e-01, 7.37580690e-01, 7.25814767e-02,
        7.05435539e-01],
       [2.64090151e-01, 7.26221251e-01, 1.97477526e-01, 3.55441609e-01,
        8.61898372e-01],
       [9.03451366e-01, 5.48286442e-01, 3.39492005e-02, 7.64641777e-01,
        3.90773333e-04]])

In [34]:
np.random.rand(4)

array([0.01546976, 0.27360767, 0.76008441, 0.22280258])

#### Standard Normal  distribution random number(returns random values between -infinity and +inifinity. The random values would follow a normal distribution with a mean value 0 and a standard deviation 1.)

In [28]:
np.random.randn(5,5)

array([[ 0.99099072, -0.87056943, -1.83446981, -0.61796747, -0.07286877],
       [-0.76203761, -1.0519566 , -0.43306474,  0.65613659,  0.40903734],
       [ 0.9565026 , -0.87953582,  1.37053786, -1.62634267, -0.27731448],
       [ 0.11520694, -0.49088393, -1.0314234 , -0.21286209,  0.72661921],
       [-0.89053897, -0.46204211,  0.3848254 ,  0.03437021,  1.95041376]])

#### Create Random integer

In [30]:
np.random.randint(1,10)

3

#### Seed with Random number - It gives the same random number every time

In [37]:
np.random.seed(20)
np.random.rand(4)

array([0.5881308 , 0.89771373, 0.89153073, 0.81583748])

#### Reshape 1D to 2D

In [38]:
np.random.rand(9).reshape(3,3)

array([[0.03588959, 0.69175758, 0.37868094],
       [0.51851095, 0.65795147, 0.19385022],
       [0.2723164 , 0.71860593, 0.78300361]])

#### Returns max and min value

In [39]:
arr = np.arange(0,10)
arr.max()

9

In [40]:
arr.min()

0

#### Return index of max and min value

In [41]:
arr.argmax()

9

In [42]:
arr.argmin()

0

## Array Slicing

#### Slice row and column in 1D Array

In [43]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
arr[3:5]

array([3, 4])

In [46]:
arr[:5]

array([0, 1, 2, 3, 4])

#### Slice row and column in 2D Array

In [48]:
arr = np.arange(0,20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
arr[2:3]

array([[ 8,  9, 10, 11]])

In [ ]:
arr[2:3]

In [62]:
arr[1:3 , 1:3]

array([[ 5,  6],
       [ 9, 10]])

## Array Filter

#### Filter by Condition

In [63]:
arr > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Operations

#### 2D sum, Row/column wise sum and mean

In [65]:
arr.sum()

190

In [69]:
arr.sum(axis = 0)

array([40, 45, 50, 55])

In [67]:
arr.sum(axis = 1)

array([ 6, 22, 38, 54, 70])

#### Understanding of Matrix Multiplication

In [73]:
arr = np.arange(0,4).reshape(2,2)
arr1 = np.arange(0,4).reshape(2,2)
print(arr)
print(arr1)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


In [72]:
arr @ arr1

array([[ 2,  3],
       [ 6, 11]])

In [74]:
arr.dot(arr1)

array([[ 2,  3],
       [ 6, 11]])

#### Return a contiguous flattened array

In [76]:
arr.ravel()

array([0, 1, 2, 3])

#### Return a copy of flattened array from 2D array

In [75]:
arr.flatten()

array([0, 1, 2, 3])

#### Sort 1D, 2D array based on index

In [77]:
arr.argsort()

array([[0, 1],
       [0, 1]], dtype=int64)

In [78]:
arr2 = np.array([4,5,1,2])
arr2.argsort()

array([2, 3, 0, 1], dtype=int64)

#### Unravel index , ravel_multi_index from stack overflow

In [5]:
X = np.array([[4,  2],
              [9,  3],
              [8,  5],
              [3,  3],
              [5,  6]])
X.shape = (5, 2)

Find, where all the value 3 presents in X


In [4]:
idx = np.where(X==3)
idx 

(array([1, 3, 3], dtype=int64), array([1, 0, 1], dtype=int64))

it returns the x, y of indices [because X is 2 dimensional]

If you apply ravel_multi_index for idx obtained

In [5]:
idx_flat = np.ravel_multi_index(idx, X.shape)
idx_flat

array([3, 6, 7], dtype=int64)

From the above example, we can understand,

ravel_multi_index converts multi-dimensional indices(nd array) into single-dimensional indices(linear array)
It works only on indices i.e. both input and output are indices
The result indices will be direct indices of X.ravel(). You can verify in the below x_linear

In [6]:
x_linear = X.ravel()
x_linear

array([4, 2, 9, 3, 8, 5, 3, 3, 5, 6])

Whereas, unravel_index is very simple, just reverse of above(np.ravel_multi_index)

In [9]:
idx = np.unravel_index(idx_flat , X.shape)
idx

(array([1, 3, 3], dtype=int64), array([1, 0, 1], dtype=int64))

which is same as idx = np.where(X==3)

unravel_index converts single-dimensional indices(linear array) into multi-dimensional indices(nd array)
It works only on indices i.e. both input and output are indices 

#### Check the type of elements

In [9]:
X.dtype

dtype('int32')

##### Check datatype

In [8]:
type(X) 

numpy.ndarray