## Pytorch Tensor Basics

Tensor is a multi-dimensional matrix containing elements of a single data type. It designed to work with GPU more effeciently and it is only one standout when compare to numpy

Here we will see 

1) How to create tensor from scratch<br>
2) Convert Numpy Array to Tensor and vice versa<br>
3) Tensor Operations 

#### Tensor Types

Scalars are 0-D tensor (ex:6,7,"ba")<br>
Vectors are 1-D tensors (ex: [3,5])<br>
Matrices are 2-D tensors (ex: <br>
[[3,5]<br>
&nbsp; [4,8]])<br>
N-Dimensional matrices are N-D tensors( ex: <br>
[[[3,5],[7,5]]<br>
[[3,5],[7,5]]])<br>
                      


In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'1.5.0'

#### Get/Set default data type of tensor

In [4]:
torch.get_default_dtype()

torch.float32

In [7]:
torch.set_default_dtype(torch.float16)
torch.get_default_dtype()

torch.float16

In [8]:
torch.set_default_dtype(torch.float32)

#### Check whether given object is tensor

In [11]:
arr = torch.Tensor([[3,4,6,7],[5,6,8,9]])
torch.is_tensor(arr)

True

#### Compute number of elements in tensor

In [12]:
torch.numel(arr)

8

#### Size/Shape of Tensor

In [15]:
print(arr.size())
print(arr.shape)

torch.Size([2, 4])
torch.Size([2, 4])


#### Tensor vs tensor vs FloatTensor vs Type Specific Tensor

'Tensor' is nothing but the alias of FloatTensor
'tensor' chooses the type based on input values

In [42]:
arr = torch.tensor([[3,4,6,7],[5,6,8,9]])
print(arr.dtype,arr.type())

torch.int64 torch.LongTensor


In [43]:
arr = torch.Tensor([[3,4,6,7],[5,6,8,9]])
print(arr.dtype,arr.type())

torch.float32 torch.FloatTensor


In [51]:
arr = torch.tensor([[3.0,4,6,7],[5,6,8,9]])
print(arr.dtype,arr.type())

torch.float32 torch.FloatTensor


In [52]:
arr = torch.tensor([[3.0,4,6,7],[5,6,8,9]],dtype=torch.half)
print(arr.dtype,arr.type())

torch.float16 torch.HalfTensor


In [45]:
arr = torch.ShortTensor([[3,4,6,7],[5,6,8,9]])
print(arr.dtype,arr.type())

torch.int16 torch.ShortTensor


#### Change the Data Type of elements

In [40]:
arr = arr.type(torch.float32)
print(arr.dtype,arr.type() )

torch.float32 torch.FloatTensor


### Tensor Types
<table style="display: inline-block">
<caption style="text-align: center"><strong>Tensor Types</strong></caption>
<tr><th>DataType</th><th>CPU tensor</th><th>GPU tensor</th></tr>
<tr><td>torch.float32 or torch.float</td><td>torch.FloatTensor</td><td>torch.cuda.FloatTensor</td></tr>
<tr><td>torch.float64 or torch.double</td><td>torch.DoubleTensor</td><td>torch.cuda.DoubleTensor</td></tr>
<tr><td>torch.float16 or torch.half</td><td>torch.HalfTensor</td><td>torch.cuda.HalfTensor</td></tr>
<tr><td>torch.uint8</td><td>torch.ByteTensor</td><td>torch.cuda.ByteTensor</td></tr>
<tr><td>torch.int8</td><td>torch.CharTensor</td><td>torch.cuda.CharTensor</td></tr>
<tr><td>torch.int16 or torch.short</sup></td><td>torch.ShortTensor</td><td>torch.cuda.ShortTensor</td></tr>

<tr><td>torch.int32 or torch.int</td><td>torch.IntTensor</td><td>torch.cuda.IntTensor</td></tr>
<tr><td>torch.int64 or torch.long</td><td>torch.LongTensor</td><td>torch.cuda.LongTensor</td></tr>
<tr><td>torch.bool</sup></td><td>torch.BoolTensor</td><td>torch.cuda.BoolTensor</td></tr>
<tr><td>&nbsp;</td><td></td><td></td></tr>
</table>

#### Clamp Tensor

Clamp all elements in input into the range [ min, max ] and return a resulting tensor

In [54]:
arr = torch.Tensor([[3,4,6,7],[5,6,8,9]])
arr = torch.clamp(arr,4,5)
arr

tensor([[4., 4., 5., 5.],
        [5., 5., 5., 5.]])

#### Numpy to Tensor

In [58]:
narr = np.random.rand(3,3)
arr = torch.from_numpy(narr)
print(narr,type(narr))
print(arr,type(arr))

[[0.30795413 0.87188764 0.12118643]
 [0.58364904 0.24250191 0.2358866 ]
 [0.93617457 0.8092996  0.82627865]] <class 'numpy.ndarray'>
tensor([[0.3080, 0.8719, 0.1212],
        [0.5836, 0.2425, 0.2359],
        [0.9362, 0.8093, 0.8263]], dtype=torch.float64) <class 'torch.Tensor'>


###### Convert to tensor(not new copy)  - Change in numpy array will also reflect in tensor

In [60]:
narr[1] = 100
print(narr,type(narr))
print(arr,type(arr))

[[  0.30795413   0.87188764   0.12118643]
 [100.         100.         100.        ]
 [  0.93617457   0.8092996    0.82627865]] <class 'numpy.ndarray'>
tensor([[  0.3080,   0.8719,   0.1212],
        [100.0000, 100.0000, 100.0000],
        [  0.9362,   0.8093,   0.8263]], dtype=torch.float64) <class 'torch.Tensor'>


#### Create a new copy of tensor from numpy



In [63]:
narr = np.random.rand(3,3)
arr = torch.Tensor(narr)
narr[1] = 100
print(narr,type(narr))
print(arr,type(arr))

[[  0.74176641   0.15614806   0.70746879]
 [100.         100.         100.        ]
 [  0.98349834   0.53651889   0.30387185]] <class 'numpy.ndarray'>
tensor([[0.7418, 0.1561, 0.7075],
        [0.1275, 0.7222, 0.7927],
        [0.9835, 0.5365, 0.3039]]) <class 'torch.Tensor'>


#### Returns a tensor filled with uninitialized data

In [65]:
arr = torch.Tensor(2,2)
arrEmpty = torch.empty(2,2)
print(arr,type(arr))
print(arrEmpty,type(arrEmpty))

tensor([[5.8239e+09, 2.4822e+00],
        [1.0286e-38, 1.0653e-38]]) <class 'torch.Tensor'>
tensor([[ 0.0000e+00,  0.0000e+00],
        [-3.9741e-18,  4.5916e-41]]) <class 'torch.Tensor'>


#### Create zero, one matrix with data type

In [72]:
zeros = torch.zeros(3,3)
ones = torch.ones(3,3, dtype=torch.float16)
oneslike= torch.ones_like(ones) #derives the shape from input array
print(zeros,type(zeros))
print(ones,type(ones))
print(oneslike,type(oneslike))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) <class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16) <class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16) <class 'torch.Tensor'>


#### Create Tensor based on ranges

argmax - gets max index in array<br>
argmin - get min index in array<br>
argsort- returns indexes based on sorted value<br>
sort - retuen list of sorted values and indexes

In [85]:
rangeTensor = torch.arange(0,9)
print(rangeTensor,type(rangeTensor))
print("Argmax", rangeTensor.argmax())
print("Argmin", rangeTensor.argmin())
print("Argsort", rangeTensor.argsort())
print("sort", rangeTensor.sort())
rangeTensor = rangeTensor.reshape(3,3)
print(rangeTensor,type(rangeTensor))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) <class 'torch.Tensor'>
Argmax tensor(8)
Argmin tensor(0)
Argsort tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
sort torch.return_types.sort(
values=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]),
indices=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]))
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) <class 'torch.Tensor'>


#### Create Evenly Space Distribution Tensor

In [88]:
arr = torch.linspace(0,50,10) #Gives 10 number between range 0 & 50
print(arr,type(arr))

tensor([ 0.0000,  5.5556, 11.1111, 16.6667, 22.2222, 27.7778, 33.3333, 38.8889,
        44.4444, 50.0000]) <class 'torch.Tensor'>


#### Python list to Tensor

In [89]:
torch.Tensor([3,6,8,9])

tensor([3., 6., 8., 9.])

#### Create Uniform distributed random number(means every number between 0 and 1 has a same probability of getting chosen)

In [91]:
arr = torch.rand(3,3)
print(arr,type(arr))

tensor([[0.4997, 0.6042, 0.1572],
        [0.7525, 0.8477, 0.0434],
        [0.1848, 0.2037, 0.2908]]) <class 'torch.Tensor'>


#### Standard Normal distribution random number(returns random values between -infinity and +inifinity. The random values would follow a normal distribution with a mean value 0 and a standard deviation 1.)

In [92]:
arr = torch.randn(3,3)
print(arr,type(arr))

tensor([[-0.2873,  0.1830,  0.4637],
        [ 0.3695, -0.0958, -0.9144],
        [-1.3614, -2.4301, -1.1042]]) <class 'torch.Tensor'>


#### Create a Random integer tensor

In [95]:
arr = torch.randint(0,9,(3,3))
print(arr,type(arr))

tensor([[6, 1, 5],
        [4, 1, 2],
        [6, 8, 6]]) <class 'torch.Tensor'>


##### Create random tensor with input size
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand_like'><strong><tt>torch.rand_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn_like'><strong><tt>torch.randn_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint_like'><strong><tt>torch.randint_like(input,low,high)</tt></strong></a><br> these return random number tensors with the same size as <tt>input</tt>

In [98]:
torch.randint_like(arr,0,10)

tensor([[2, 3, 1],
        [6, 2, 2],
        [7, 9, 8]])

#### Seed with Random number - It gives the same random number every time(manual_seed)

In [103]:
torch.manual_seed(50)
arr = torch.randint(0,9,(3,3))
print(arr,type(arr))

tensor([[4, 0, 1],
        [1, 2, 6],
        [4, 7, 3]]) <class 'torch.Tensor'>


#### Change the dimension of tensor using Squeeze/UnSqueeze

Unsqueeze - Adds a new dimension to tensor<br>Squeeze - Removes the dimension from tensor

In [106]:
t1 = torch.rand(3,3)
t1

tensor([[0.9634, 0.1230, 0.4048],
        [0.4985, 0.9987, 0.6049],
        [0.5229, 0.6974, 0.2505]])

In [107]:
t2 = torch.unsqueeze(t1,2)

In [108]:
t2.shape

torch.Size([3, 3, 1])

In [109]:
t3 = torch.squeeze(t2,2)

In [110]:
t3.shape

torch.Size([3, 3])

### Device of tensor

In [111]:
t1.device

device(type='cpu')

# Tensor Operations

#### Slice row and column in Tensor(same like numpy)

In [114]:
arr = torch.randint(0,9,(3,3))
print("Whole Tensor", arr, arr.dtype )

Whole Tensor tensor([[0, 5, 5],
        [6, 2, 5],
        [7, 1, 3]]) torch.int64


In [121]:
print("Expected [7,1,3]", arr[2:], arr.dtype )
print("Expected [[5],[3]]", arr[1:, 2:], arr.dtype )

Expected [7,1,3] tensor([[7, 1, 3]]) torch.int64
Expected [[5],[3]] tensor([[5],
        [3]]) torch.int64


##### View vs Reshape - Both does the same thing. 

From Pytorch documentation

PyTorch allows a tensor to be a View of an existing tensor. View tensor shares the same underlying data with its base tensor. Supporting View avoids explicit data copy, thus allows us to do fast and memory efficient reshaping, slicing and element-wise operations.



In [132]:
arr = torch.arange(20)
print(arr,type(arr))

viewarr = arr.view(4,5)
print("view of (4,5)",viewarr,type(viewarr))
arr[1] = 100 #it changes the value in view refence too
print("change the 1st index to 100",arr,type(arr))
print("changed value ",viewarr,type(viewarr)) 
viewarr[1] = 200
print("change the 1 row to 200",viewarr,type(viewarr)) 
print("changed value ",arr,type(arr))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]) <class 'torch.Tensor'>
view of (4,5) tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]) <class 'torch.Tensor'>
change the 1st index to 100 tensor([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19]) <class 'torch.Tensor'>
changed value  tensor([[  0, 100,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19]]) <class 'torch.Tensor'>
change the 1 row to 200 tensor([[  0, 100,   2,   3,   4],
        [200, 200, 200, 200, 200],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19]]) <class 'torch.Tensor'>
changed value  tensor([  0, 100,   2,   3,   4, 200, 200, 200, 200, 200,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19]) <class 'torch.Tensor'>


##### View this tensor as the same size as other tensor(view_as)

In [134]:
arr.view_as(viewarr)

tensor([[  0, 100,   2,   3,   4],
        [200, 200, 200, 200, 200],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19]])

#### Transpose the tensor

In [5]:
arr = torch.arange(20).reshape(5,4)
transposearr = arr.transpose(0,1) 
print("Expected size (4,5)", transposearr,transposearr.shape )
transposearr = torch.transpose(arr,0,1) 
print("Expected size (4,5)", transposearr,transposearr.shape )

Expected size (4,5) tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]]) torch.Size([4, 5])
Expected size (4,5) tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]]) torch.Size([4, 5])


#### Unbind tensor into different tuple of tensors

In [6]:
arr = torch.arange(20).reshape(5,4)
print(arr,type(arr))
torch.unbind(arr)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]) <class 'torch.Tensor'>


(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11]),
 tensor([12, 13, 14, 15]),
 tensor([16, 17, 18, 19]))

#### Infer Tensor with Views(means view can identify either X or Y shape based on number of element and X/Y shape)

In [9]:
arr = torch.arange(20)

#just pass -1 in place of dimension it can infer it..
print(arr.view(5,-1))
print(arr.view(-1,5))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


### Arthimetic Operations

In [11]:
a = torch.tensor([[1,2,3],[1,2,3]], dtype=torch.float)
b = torch.tensor([[5,5,5],[6,6,6]], dtype=torch.float)
print(a + b)

tensor([[6., 7., 8.],
        [7., 8., 9.]])


In [12]:
torch.mul(a,b)

tensor([[ 5., 10., 15.],
        [ 6., 12., 18.]])

#### In-place operations

In [16]:
print(a)
#underscore function for in-place change
a.div_(2) #same as a = a.div(2)
print(a)

tensor([[0.1250, 0.2500, 0.3750],
        [0.1250, 0.2500, 0.3750]])
tensor([[0.0625, 0.1250, 0.1875],
        [0.0625, 0.1250, 0.1875]])


#### Out tensor as argument

In [17]:
result = torch.empty(4)
torch.add(a, b, out=result)  # equivalent to result=torch.add(a,b)
print(result)

tensor([[5.0625, 5.1250, 5.1875],
        [6.0625, 6.1250, 6.1875]])


#### Chunk vs Cat

chunks - Splits a tensor into a specific number of chunks<br>
cat - merge chunks into one tensor

In [35]:
arr= torch.arange(0,9).reshape(3,3)
print(arr)
rowchunk = torch.chunk(arr, 3, 0)
colchunk = torch.chunk(arr, 3, 1)
print(rowchunk,colchunk)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
(tensor([[0, 1, 2]]), tensor([[3, 4, 5]]), tensor([[6, 7, 8]])) (tensor([[0],
        [3],
        [6]]), tensor([[1],
        [4],
        [7]]), tensor([[2],
        [5],
        [8]]))


In [37]:
newTensor= torch.tensor([[8, 9, 5]])
torch.cat((rowchunk[0], rowchunk[1],rowchunk[2], newTensor), 0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [8, 9, 5]])

### Other Tensor Operations
<table style="display: inline-block">
<caption style="text-align: center"><strong>Arithmetic</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>a + b</td><td>a.add(b)</td><td>element wise addition</td></tr>
<tr><td>a - b</td><td>a.sub(b)</td><td>subtraction</td></tr>
<tr><td>a * b</td><td>a.mul(b)</td><td>multiplication</td></tr>
<tr><td>a / b</td><td>a.div(b)</td><td>division</td></tr>
<tr><td>a % b</td><td>a.fmod(b)</td><td>modulo (remainder after division)</td></tr>
<tr><td>a<sup>b</sup></td><td>a.pow(b)</td><td>power</td></tr>
<tr><td>&nbsp;</td><td></td><td></td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Monomial Operations</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>|a|</td><td>torch.abs(a)</td><td>absolute value</td></tr>
<tr><td>1/a</td><td>torch.reciprocal(a)</td><td>reciprocal</td></tr>
<tr><td>$\sqrt{a}$</td><td>torch.sqrt(a)</td><td>square root</td></tr>
<tr><td>log(a)</td><td>torch.log(a)</td><td>natural log</td></tr>
<tr><td>e<sup>a</sup></td><td>torch.exp(a)</td><td>exponential</td></tr>
<tr><td>12.34  ==>  12.</td><td>torch.trunc(a)</td><td>truncated integer</td></tr>
<tr><td>12.34  ==>  0.34</td><td>torch.frac(a)</td><td>fractional component</td></tr>
</table>

<table style="display: inline-block">
<caption style="text-align: center"><strong>Trigonometry</strong></caption>
<tr><th>OPERATION</th><th>FUNCTION</th><th>DESCRIPTION</th></tr>
<tr><td>sin(a)</td><td>torch.sin(a)</td><td>sine</td></tr>
<tr><td>cos(a)</td><td>torch.sin(a)</td><td>cosine</td></tr>
<tr><td>tan(a)</td><td>torch.sin(a)</td><td>tangent</td></tr>
<tr><td>arcsin(a)</td><td>torch.asin(a)</td><td>arc sine</td></tr>
<tr><td>arccos(a)</td><td>torch.acos(a)</td><td>arc cosine</td></tr>
<tr><td>arctan(a)</td><td>torch.atan(a)</td><td>arc tangent</td></tr>
<tr><td>sinh(a)</td><td>torch.sinh(a)</td><td>hyperbolic sine</td></tr>
<tr><td>cosh(a)</td><td>torch.cosh(a)</td><td>hyperbolic cosine</td></tr>
<tr><td>tanh(a)</td><td>torch.tanh(a)</td><td>hyperbolic tangent</td></tr>
</table>

## Matrix Muliplication vs Dot

<b>Dot Product</b>
A <a href='https://en.wikipedia.org/wiki/Dot_product'>dot product</a> is the sum of the products of the corresponding entries of two 1D tensors. If the tensors are both vectors, the dot product is given as:<br>

$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d & e & f \end{bmatrix} = ad + be + cf$

If the tensors include a column vector, then the dot product is the sum of the result of the multiplied matrices. For example:<br>
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d \\ e \\ f \end{bmatrix} = ad + be + cf$<br><br>
Dot products can be expressed as <a href='https://pytorch.org/docs/stable/torch.html#torch.dot'><strong><tt>torch.dot(a,b)</tt></strong></a> or `a.dot(b)` or `b.dot(a)`

<b>Matrix multiplication</b>
2D Matrix multiplication is possible when the number of columns in tensor <strong><tt>A</tt></strong> matches the number of rows in tensor <strong><tt>B</tt></strong>. In this case, the product of tensor <strong><tt>A</tt></strong> with size $(x,y)$ and tensor <strong><tt>B</tt></strong> with size $(y,z)$ results in a tensor of size $(x,z)$
<div>
<div align="left"><img src='../Images/matrixmultiply.png' align="left"><br><br>

Matrix multiplication can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.mm'><strong><tt>torch.mm(a,b)</tt></strong></a> or `a.mm(b)` or `a @ b`

In [40]:
x = torch.tensor([1,2,3], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)
print(x.mul(y)) 
print(x.dot(y))

tensor([ 4., 10., 18.])
tensor(32.)


In [54]:
x = torch.arange(0,20).reshape(5,4)
y = torch.arange(0,24).reshape(4,6)

z= x.mm(y)
print("Matrix Multiplication Expected  5X6", z, z.shape)

x1 = torch.arange(0,4)
print("Matrix Vector Multiplication", x.mv(x1))

Matrix Multiplication Expected  5X6 tensor([[  84,   90,   96,  102,  108,  114],
        [ 228,  250,  272,  294,  316,  338],
        [ 372,  410,  448,  486,  524,  562],
        [ 516,  570,  624,  678,  732,  786],
        [ 660,  730,  800,  870,  940, 1010]]) torch.Size([5, 6])
Matrix Vector Multiplication tensor([ 14,  38,  62,  86, 110])


#### fill the tensor

In [56]:
arr = torch.arange(0,4)
arr.new_full([2, 2], fill_value=5)

tensor([[5, 5],
        [5, 5]])

#### Refereces

https://pytorch.org/docs/stable/tensors.html